export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_RESPONSE = 'GET_ITEMS_RESPONSE';
export const GET_ITEMS_RESPONSE_FAIL = 'GET_ITEMS_RESPONSE_FAIL';

export const FILTER_SHAPE_CREATED = 'FILTER_SHAPE_CREATED';
export const SELECTED_FILTER = 'SELECTED_FILTER';

export const SORT_ORDER_SELECTED = 'SORT_ORDER_SELECTED';
